# Generated by Django 4.1.2 on 2023-07-27 11:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_checklistcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistcategory',
            name='checklist_type',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
